/**
 * Inline AI Diff Annotations & Steering System
 *
 * Inspired by Orca's diff annotation workflow: allows users or reviewers to
 * attach line-specific feedback to code changes generated by AI runs.
 * The accumulated comments are then formatted into an actionable, structured
 * steering prompt for refinement without requiring manual contextual descriptions.
 */

export type DiffCommentSide = "old" | "new";

export interface DiffComment {
  id: string;
  filePath: string;
  lineNumber: number;
  comment: string;
  originalLine?: string;
  side?: DiffCommentSide;
  createdAt: number;
}

export interface DiffAnnotationBatch {
  comments: DiffComment[];
  updatedAt: number;
}

/**
 * Creates an empty diff annotation batch.
 */
export function createEmptyDiffBatch(): DiffAnnotationBatch {
  return {
    comments: [],
    updatedAt: Date.now(),
  };
}

/**
 * Creates a unique diff comment object.
 */
export function createDiffComment(
  filePath: string,
  lineNumber: number,
  comment: string,
  originalLine?: string,
  side: DiffCommentSide = "new"
): DiffComment {
  const cleanPath = filePath.replace(/\\/g, "/").trim();
  const id = `diff-comm-${Math.random().toString(36).slice(2, 9)}-${Date.now()}`;
  return {
    id,
    filePath: cleanPath,
    lineNumber: Math.max(1, Math.floor(lineNumber)),
    comment: comment.trim(),
    originalLine: originalLine ? originalLine.trim() : undefined,
    side,
    createdAt: Date.now(),
  };
}

/**
 * Adds or updates a comment in the batch.
 */
export function addCommentToBatch(
  batch: DiffAnnotationBatch,
  comment: DiffComment
): DiffAnnotationBatch {
  const filtered = batch.comments.filter(
    (c) => !(c.filePath === comment.filePath && c.lineNumber === comment.lineNumber && c.side === comment.side)
  );

  return {
    comments: [...filtered, comment],
    updatedAt: Date.now(),
  };
}

/**
 * Removes a specific comment by its ID.
 */
export function removeCommentFromBatch(
  batch: DiffAnnotationBatch,
  commentId: string
): DiffAnnotationBatch {
  return {
    comments: batch.comments.filter((c) => c.id !== commentId),
    updatedAt: Date.now(),
  };
}

/**
 * Clears all comments associated with a given file path.
 */
export function clearCommentsForFile(
  batch: DiffAnnotationBatch,
  filePath: string
): DiffAnnotationBatch {
  const cleanPath = filePath.replace(/\\/g, "/").trim();
  return {
    comments: batch.comments.filter((c) => c.filePath !== cleanPath),
    updatedAt: Date.now(),
  };
}

/**
 * Groups comments in a batch by their normalized file paths.
 */
export function groupCommentsByFile(
  batch: DiffAnnotationBatch
): Record<string, DiffComment[]> {
  const grouped: Record<string, DiffComment[]> = {};
  for (const c of batch.comments) {
    if (!grouped[c.filePath]) {
      grouped[c.filePath] = [];
    }
    grouped[c.filePath].push(c);
  }

  for (const filePath of Object.keys(grouped)) {
    grouped[filePath].sort((a, b) => a.lineNumber - b.lineNumber);
  }

  return grouped;
}

/**
 * Formats a batch of diff comments into a structured steering prompt for the AI agent.
 */
export function formatDiffFeedbackPrompt(batch: DiffAnnotationBatch): string {
  if (!batch.comments || batch.comments.length === 0) {
    return "";
  }

  const grouped = groupCommentsByFile(batch);
  const fileCount = Object.keys(grouped).length;
  const totalComments = batch.comments.length;

  const lines: string[] = [
    `I have reviewed your changes and noted ${totalComments} inline annotation(s) across ${fileCount} file(s).`,
    `Please refine the code to resolve each item listed below:`,
    "",
  ];

  for (const [filePath, comments] of Object.entries(grouped)) {
    lines.push(`### File: \`${filePath}\``);
    for (const c of comments) {
      const sideLabel = c.side === "old" ? " (original version)" : "";
      if (c.originalLine) {
        lines.push(`- Line ${c.lineNumber}${sideLabel}: \`${c.originalLine}\``);
      } else {
        lines.push(`- Line ${c.lineNumber}${sideLabel}:`);
      }
      lines.push(`  Feedback: ${c.comment}`);
    }
    lines.push("");
  }

  lines.push(`Please apply these changes directly and verify that tests still pass.`);
  return lines.join("\n").trim();
}
